[workspace]
members = [
  "copy",
  "daemon",
  "data",
  "e2e",
  "git-ext",
  "git-helpers",
  "librad",
  "macros",
  "seed",
  "std-ext",
  "test",
]

[patch.crates-io.git2]
git = "https://github.com/radicle-dev/git2-rs.git"
rev = "9f4101f632d33fdba72b2fe0614a790259c1f6f3"

[patch.crates-io.libgit2-sys]
git = "https://github.com/radicle-dev/git2-rs.git"
rev = "9f4101f632d33fdba72b2fe0614a790259c1f6f3"

