[package]
name = "librad"
version = "0.1.0"
authors = ["Monadic <team@monadic.xyz>"]
edition = "2018"

[dependencies]
async-std = "1.4"
bs58 = { version = "0.3", features = ["check"] }
futures_codec = "0.3"
futures_cbor_codec = "0.2"
directories = "2.0"
failure = { version = "0.1", features = ["backtrace"] }
failure_derive = "0.1"
futures = "0.3"
git2 = "0.10"
lazy_static = "1.4"
libp2p = { version = "0.14.0-alpha.1", default-features = false, features = [] }
log = "0.4"
nettle = { version = "5.0", features = ["vendored"]  }
nonempty = "0.1"
olpc-cjson = "0.1"
radicle-surf = { git = "https://github.com/radicle-dev/radicle-surf", rev = "58a0e6680d61cc312eee3255abe5d0d494f631d2" }
regex = "1.3"
secstr = "0.3"
sequoia-openpgp = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10"
serde_json = "1.0"
sha2 = "0.8"
sodiumoxide = "0.2"
tempfile = "3.1"
url = { version = "2.1", features = ["serde"] }
urltemplate = "0.1"

[dev-dependencies]
proptest = "0.9"
