steps:
- label: "fast"
  commands:
  - "cargo fmt -- --check"
  - "cargo test --all"
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-link-build@sha256:fc5eded79ac8af38482e4fb54ec6dfb16e04a3fff2c3a061a60602b827b9f54e"
    DOCKER_FILE: .buildkite/docker/rust/Dockerfile

- label: "Latest Stable Rust"
  commands:
  - "cargo test --all"
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_FILE: .buildkite/docker/rust/Dockerfile
  soft_fail: true
  concurrency_group: "radicle-link/slow"
  concurrency: 1

- label: "Nightly Rust"
  commands:
  - "cargo test --all"
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_FILE: .buildkite/docker/rust-nightly/Dockerfile
  soft_fail: true
  concurrency_group: "radicle-link/slow"
  concurrency: 1

- label: "Render Spec"
  commands:
  - "cd spec"
  - "make clean all"
  - "git diff --exit-code -- spec/out"
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-link-pandoc@sha256:eb1d9592d83fa5edad1b626a71b53aa586c64a5a7e7bb4158256d6265e1ac1a9"
    DOCKER_FILE: .buildkite/docker/pandoc/Dockerfile
