steps:
  # This step is essentially a no-op. Since it blocks all other steps, we avoid
  # triggering `n` image builds when updating the `DOCKER_IMAGE`. Note that it
  # still saves about 20sec to pin the image to a SHA256 after an upgrade.
  - label: "Build container"
    if: |
        build.pull_request.repository.fork == null ||
        build.pull_request.repository.fork == false
    commands:
      - ".buildkite/env"
      - ".buildkite/build-container"
    agents: &build-agent
      production: "true"
      platform: "linux"
    env: &build-docker
      DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-link-seedling-build@sha256:a4bdc23594a970a155ac14045ec78290702bc0e6de746b4edbaf30f2b9719d9b"
      DOCKER_FILE: .buildkite/docker/rust/Dockerfile

  - wait

  - label: "Build + Test"
    timeout_in_minutes: 20
    if: |
        build.pull_request.repository.fork == null ||
        build.pull_request.repository.fork == false
    commands:
      - ".buildkite/env"
      - "ci/build-test"
    artifact_paths:
      - "Cargo.lock"
    agents: *build-agent
    env: *build-docker

  - label: "fmt + clip"
    timeout_in_minutes: 5
    if: |
        build.pull_request.repository.fork == null ||
        build.pull_request.repository.fork == false
    commands:
      - ".buildkite/env"
      - "ci/clippy"
    artifact_paths:
      - "Cargo.lock"
    agents: *build-agent
    env: *build-docker

  - label: "Deny"
    timeout_in_minutes: 1
    if: |
        build.pull_request.repository.fork == null ||
        build.pull_request.repository.fork == false
    commands:
      - ".buildkite/env"
      - "ci/advisory"
    artifact_paths:
      - "Cargo.lock"
    agents: *build-agent
    env: *build-docker

  - label: "Docs"
    timeout_in_minutes: 10
    if: |
        build.pull_request.repository.fork == null ||
        build.pull_request.repository.fork == false
    commands:
      - ".buildkite/env"
      - "ci/docs"
    artifact_paths:
      - "Cargo.lock"
    agents: *build-agent
    env: *build-docker
