env:
  DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-link-build@sha256:6b061cd8347976a6b2935e2a0389fea0b18ea856e32749947b904174e1c01e35"
  DOCKER_FILE: .buildkite/docker/rustc1.39/Dockerfile

steps:
- label: "Tests"
  command: "cargo test --all"
  agents:
    production: "true"
    platform: "linux"

- label: "Render Spec"
  command: "make -C spec all"
  artifact_paths:
  - "spec/out/*"
  agents:
    production: "true"
    platform: "linux"
