[package]
name = "rad2"
version = "0.1.0"
authors = ["Monadic <team@monadic.xyz>"]
edition = "2018"
description = "The Official Unoffical Radicle CLI"

[dependencies]
async-std = "1.4"
env_logger = "0.7"
failure = "0.1"
failure_derive = "0.1"
futures = "0.3"
git2 = "0.10"
libp2p = { version = "0.15.0", default-features = false, features = [] }
librad = { path = "../librad" }
log = "0.4"
retry = "1.0"
rpassword = "4.0"
secstr = "0.3"
serde = "1.0"
serde_yaml = "0.8"
structopt = "0.3"
tempfile = "3.1"
tokio = "0.1"
tokio-codec = "0.1"
tokio-executor = "0.1"
tokio-io = "0.1"
url = "2.1"

