[package]
name = "rad2"
version = "0.1.0"
authors = ["Monadic <team@monadic.xyz>"]
edition = "2018"

[dependencies]
clap = { version = "2.33", features = ["suggestions", "color"] }
failure = "0.1"
failure_derive = "0.1"
librad2 = { path = "../librad2" }
rpassword = "4.0"
secstr = "0.3"
