[package]
name = "rad2"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
description = "The Official Unoffical Radicle CLI"
license = "GPL-3.0-or-later"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
git2 = "0.10"
librad = { path = "../librad" }
radicle-keystore = { path = "../radicle-keystore" }
secstr = "0.3"
serde = "1.0"
serde_yaml = "0.8"
structopt = "0.3"
tempfile = "3.1"
url = "2.1"

