[package]
name = "linkd"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-or-later"
authors = [
  "xla <self@xla.is>",
]

[dependencies]
tokio   = { version = "1.10", default-features = false, features = [ "macros", "process", "rt-multi-thread" ] }

[dependencies.node-lib]
path    = "../../node-lib"
version = "0.1.0"
