[package]
name = "radicle-tracker"
version = "0.1.0"
authors = ["FintanH <fintan.halpenny@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.5"
nonempty = "0.2"
thiserror = "1.0"
