[package]
name = "radicle-tracker"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nonempty = "0.4"
num-bigint = "0.2"
thiserror = "1.0"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
itertools = "0.9"
num-bigint = "0.2"
proptest = "0.9"
pretty_assertions = "0.6"
