[package]
name = "radicle-tracker"
version = "0.1.0"
authors = ["FintanH <fintan.halpenny@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nonempty = { git = "https://github.com/cloudhead/nonempty", rev = "master" }
thiserror = "1.0"
time = "0.2"
