[package]
name = "link-cbor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1"
minicbor = "0.9.1"
serde_json = "1.0"

[dependencies.link-canonical]
path = "../link-canonical"