name: ci
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - run: ./scripts/ci/clippy
        shell: bash

  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - run: ./scripts/ci/build-test
        shell: bash
      - run: ./scripts/ci/build-bins
        shell: bash

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - run: ./scripts/ci/build-test
        shell: bash
      - run: ./scripts/ci/build-bins
        shell: bash

  windows:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - run: ./scripts/ci/test-fast
        shell: bash
