name: docs
on:
  push:
    paths:
      - 'docs/**'
jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: render
        uses: ./.github/actions/pandoc
        id: pandoc
        with:
            cmd: cd docs/spec && make clean all
      - name: check unchanged
        shell: bash
        run: git diff --exit-code -- docs
